### ISSUE TITLE
.gitignore isn't being properly appended

### ISSUE THREAD

**Issue by eatspaint** [jakesorce/webpack-rails-react#17]
[add_to_gitignore](https://github.com/cottonwoodcoding/repack/blob/master/lib/generators/repack/install_generator.rb#L118) doesn't seem to insert a newline before appending `.gitignore`, resulting in the pre-existing last line of the file breaking because of the inserted comment.

Example: 

``` /config/database.yml
/config/katamari-db.yml
/config/torquebox.yml
/db/schema.rb
/log/
/tmp/
bin/
/gems/
/public/assets/
.ruby-version# Added by repack
/node_modules
/public/webpack
```

`.ruby-version` is now no longer ignored, due to the comment.

**Comment by eatspaint** [comment]
Just looked at an old diff of my `.gitignore`, it looks like there wasn't a newline at the end of the file to begin with. So maybe the script should check for a newline? Or just default to adding one before appending anyways?

**Comment by wdjungst** [comment]
Fixed
